#!/bin/bash
./benchGen 1, examples/ex0/production_rule.txt examples/ex0/seed_string.txt outs/1_0_array array
./benchGen 1, examples/ex1/production_rule.txt examples/ex1/seed_string.txt outs/1_1_array array
./benchGen 1, examples/ex2/production_rule.txt examples/ex2/seed_string.txt outs/1_2_array array
./benchGen 1, examples/ex3/production_rule.txt examples/ex3/seed_string.txt outs/1_3_array array
./benchGen 1, examples/ex4/production_rule.txt examples/ex4/seed_string.txt outs/1_4_array array
./benchGen 1, examples/ex5/production_rule.txt examples/ex5/seed_string.txt outs/1_5_array array
./benchGen 1, examples/ex6/production_rule.txt examples/ex6/seed_string.txt outs/1_6_array array
./benchGen 1, examples/ex7/production_rule.txt examples/ex7/seed_string.txt outs/1_7_array array
./benchGen 1, examples/ex8/production_rule.txt examples/ex8/seed_string.txt outs/1_8_array array
./benchGen 1, examples/ex9/production_rule.txt examples/ex9/seed_string.txt outs/1_9_array array
./benchGen 2, examples/ex0/production_rule.txt examples/ex0/seed_string.txt outs/2_0_array array
./benchGen 2, examples/ex1/production_rule.txt examples/ex1/seed_string.txt outs/2_1_array array
./benchGen 2, examples/ex2/production_rule.txt examples/ex2/seed_string.txt outs/2_2_array array
./benchGen 2, examples/ex3/production_rule.txt examples/ex3/seed_string.txt outs/2_3_array array
./benchGen 2, examples/ex4/production_rule.txt examples/ex4/seed_string.txt outs/2_4_array array
./benchGen 2, examples/ex5/production_rule.txt examples/ex5/seed_string.txt outs/2_5_array array
./benchGen 2, examples/ex6/production_rule.txt examples/ex6/seed_string.txt outs/2_6_array array
./benchGen 2, examples/ex7/production_rule.txt examples/ex7/seed_string.txt outs/2_7_array array
./benchGen 2, examples/ex8/production_rule.txt examples/ex8/seed_string.txt outs/2_8_array array
./benchGen 2, examples/ex9/production_rule.txt examples/ex9/seed_string.txt outs/2_9_array array
./benchGen 3, examples/ex0/production_rule.txt examples/ex0/seed_string.txt outs/3_0_array array
./benchGen 3, examples/ex1/production_rule.txt examples/ex1/seed_string.txt outs/3_1_array array
./benchGen 3, examples/ex2/production_rule.txt examples/ex2/seed_string.txt outs/3_2_array array
./benchGen 3, examples/ex3/production_rule.txt examples/ex3/seed_string.txt outs/3_3_array array
./benchGen 3, examples/ex4/production_rule.txt examples/ex4/seed_string.txt outs/3_4_array array
./benchGen 3, examples/ex5/production_rule.txt examples/ex5/seed_string.txt outs/3_5_array array
./benchGen 3, examples/ex6/production_rule.txt examples/ex6/seed_string.txt outs/3_6_array array
./benchGen 3, examples/ex7/production_rule.txt examples/ex7/seed_string.txt outs/3_7_array array
./benchGen 3, examples/ex8/production_rule.txt examples/ex8/seed_string.txt outs/3_8_array array
./benchGen 3, examples/ex9/production_rule.txt examples/ex9/seed_string.txt outs/3_9_array array
./benchGen 4, examples/ex0/production_rule.txt examples/ex0/seed_string.txt outs/4_0_array array
./benchGen 4, examples/ex1/production_rule.txt examples/ex1/seed_string.txt outs/4_1_array array
./benchGen 4, examples/ex2/production_rule.txt examples/ex2/seed_string.txt outs/4_2_array array
./benchGen 4, examples/ex3/production_rule.txt examples/ex3/seed_string.txt outs/4_3_array array
./benchGen 4, examples/ex4/production_rule.txt examples/ex4/seed_string.txt outs/4_4_array array
./benchGen 4, examples/ex5/production_rule.txt examples/ex5/seed_string.txt outs/4_5_array array
./benchGen 4, examples/ex6/production_rule.txt examples/ex6/seed_string.txt outs/4_6_array array
./benchGen 4, examples/ex7/production_rule.txt examples/ex7/seed_string.txt outs/4_7_array array
./benchGen 4, examples/ex8/production_rule.txt examples/ex8/seed_string.txt outs/4_8_array array
./benchGen 4, examples/ex9/production_rule.txt examples/ex9/seed_string.txt outs/4_9_array array
./benchGen 5, examples/ex0/production_rule.txt examples/ex0/seed_string.txt outs/5_0_array array
./benchGen 5, examples/ex1/production_rule.txt examples/ex1/seed_string.txt outs/5_1_array array
./benchGen 5, examples/ex2/production_rule.txt examples/ex2/seed_string.txt outs/5_2_array array
./benchGen 5, examples/ex3/production_rule.txt examples/ex3/seed_string.txt outs/5_3_array array
./benchGen 5, examples/ex4/production_rule.txt examples/ex4/seed_string.txt outs/5_4_array array
./benchGen 5, examples/ex5/production_rule.txt examples/ex5/seed_string.txt outs/5_5_array array
./benchGen 5, examples/ex6/production_rule.txt examples/ex6/seed_string.txt outs/5_6_array array
./benchGen 5, examples/ex7/production_rule.txt examples/ex7/seed_string.txt outs/5_7_array array
./benchGen 5, examples/ex8/production_rule.txt examples/ex8/seed_string.txt outs/5_8_array array
./benchGen 5, examples/ex9/production_rule.txt examples/ex9/seed_string.txt outs/5_9_array array
